### ISSUE TITLE
Consider providing ES6 module distribution

### ISSUE THREAD

**Issue by TomKrcmar** [gpuweb/types#109]
Currently, all WebGPU types are added to the global ambients. The option to have them scoped as a module rather than global would be very helpful for me.

Working on large projects, particularly with graphics hardware abstraction layers, types such as GPUBuffer conflict with types already in the engine. For this reason as well as for overall organization and transparency into where the symbols came from in source code, it would be nice to be able to import these types from the package at the top of our ES6 files, as a module. 

An additional distribution file that has all the export keywords added could be a solution, since `bikeshed-to-ts` does seem to have that feature, and typescript would see such a file as a module. Another idea might be to provide a dist file that simply has a declare module wrapper.

For clarity, here's an example of what I'm trying to do:
```
import type { GPUBuffer } from '@webgpu/types'
// use GPUBuffer
```
or
```
import type { GPUBuffer as WebGPUGPUBuffer } from '@webgpu/types'
// use WebGPUGPUBuffer
```
or
```
import * as WebGPU from '@webgpu/types'
// use WebGPU.GPUBuffer
```

Currently, we get
`File '.../node_modules/@webgpu/types/dist/index.d.ts' is not a module.`

**Comment by kainino0x** [comment]
Hi, thanks for the report! The WebGPU types describe a built-in API that itself *is* ambient, and therefore is correctly described by ambient definitions. For example, `GPUBuffer` is not just a type, but also an ambient global definition (for the class "constructor" object). This ambient global definition is implemented by the browser, not TypeScript, so will be there regardless of imports. That is to say, the naming conflict between your project and WebGPU is deeper than just TypeScript types - it exists at the runtime JavaScript level too.

Also, once WebGPU is stabilized, some version of these types will be migrated/snapshotted into the TypeScript core repository, which defines all of the Web Platform APIs as ambient:
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts
Once this is done they'll always be in scope when using the ["dom"](https://www.typescriptlang.org/tsconfig#lib) lib. Which means something like this would be a temporary patch only until that happens.

I think I've understood the problem correctly, hope this helps. But let me know if you think I'm off base!
