### ISSUE TITLE
Question: can I use `types` property in compilerOption of tsconfig.json

### ISSUE THREAD

**Issue by Lantianyou** [gpuweb/types#135]
According to the docs, seems we can also use `types` without webpack

https:www.typescriptlang.org/tsconfig#typeRoots

like this:
```json
{
  "compiloerOptions": {
      "types": [ "@webgpu/types"]
  }

}
```

**Comment by Lantianyou** [comment]
My point is, there is two ways to use this package, and readme section of webpack is unnecessary

**Comment by kainino0x** [comment]
Thanks for the extra method! I will definitely add it. It seems nicer than `typeRoots`.

I don't know anything about Webpack, someone contributed that bit of the instructions (cc @darionco). It seems Webpack has its own way to configure additional types. If you set the tsconfig option, do either of you know if then, you don't need the webpack.config.js option? If so, I'd prefer to remove the Webpack section.

**Comment by kainino0x** [comment]
In fact as it already says in the readme: "(may not be necessary with `tsc` config above - untested)" 🙂

**Comment by kainino0x** [comment]
BTW to clarify - the webpack instructions are definitely not needed if you don't use webpack. I just don't know if you need them if you *are* using webpack.

**Comment by Lantianyou** [comment]
Thanks for your reply. Now I see why there is a section about webpack in the first place. Luckily, I do not use Webpack.

**Comment by Lantianyou** [comment]
Feel free to close this issue. haha

**Comment by kainino0x** [comment]
Thanks for confirming! And thanks for reporting, I was able to improve the README.
