### ISSUE TITLE
GPUBuffer#mapAsync does not match spec

### ISSUE THREAD

**Issue by drawmindmap** [gpuweb/types#27]
`mapAsync(offset?: number, size?: number): Promise<void>;`
vs
`Promise<void> mapAsync(GPUMapModeFlags mode, optional GPUSize64 offset = 0, optional GPUSize64 size);`

**Comment by kainino0x** [comment]
Are you using the latest version? It should be correct now.

https://github.com/gpuweb/types/blob/main/dist/index.d.ts#L542

**Comment by drawmindmap** [comment]
My bad.
