### ISSUE TITLE
Why constant variables name haven't preffix 'GPU'

### ISSUE THREAD

**Issue by HypnosNova** [gpuweb/types#32]
For example: 
![image](https://user-images.githubusercontent.com/7953802/96545985-058a8000-12dc-11eb-9f4b-4b30d4b2c928.png)
The name is AddressMode, however in docs, most of these constant variables start with 'GPU' like this:
![image](https://user-images.githubusercontent.com/7953802/96546123-42567700-12dc-11eb-8891-9a3505ded7e0.png)

So is it a right way to define constant variables without preffix 'GPU' in d.ts file?

**Comment by kainino0x** [comment]
They can't have the same name because the two names would collide. The constants file is purely a helper thing, not actually providing anything to do with the types for WebGPU. It likely should be removed or moved to another repo.

**Comment by HypnosNova** [comment]
@kainino0x I see. So it would be better to create a new repository that we can move src folder into it. 
That repository could be used to help developers developing WebGPU projects without using magic string.

**Comment by kainino0x** [comment]
Yes, possibly. Though as I recently said on #30, `as const` may remove the need for this file at all.

**Comment by kainino0x** [comment]
Removed in #51
