### ISSUE TITLE
forceSoftware is deprecated. Use forceFallbackAdapter instead.

### ISSUE THREAD

**Issue by hjlld** [gpuweb/types#84]
Chrome Canary 97.0.4690.4 has implemented the lastest spec. It will this warning if you still use `navigator.gpu.requestAdapter( { powerPreference, forceSoftware } );`

**Comment by kainino0x** [comment]
Thanks for the report. These bindings have gotten behind the spec because of a change upstream that our generator can't handle. We're going to be looking into that. Although perhaps we can still get an update out before that... I'll look into it.

**Comment by toji** [comment]
Fixed by #86, though the generator issue is still outstanding.
